# Generated by Django 5.2.1 on 2025-07-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the league.', null=True, verbose_name='description')),
                ('start_date', models.DateField(auto_now=True, help_text='The date when the league starts.', verbose_name='start date')),
                ('end_date', models.DateField(help_text='The date when the league ends.', null=True, verbose_name='end date')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaguePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1500, help_text='The rating of a player, wich measures the skill level.', verbose_name='elo')),
                ('rd', models.FloatField(default=350, help_text='Rating Deviation: the uncertainty in the rating of a player.', verbose_name='RD')),
                ('sigma', models.FloatField(default=0.06, help_text="The volatility of the player's rating, which measures the             consistency of the player's performance.", verbose_name='vol')),
                ('matches_played', models.IntegerField(default=0, help_text='The number of matches played by the player.', verbose_name='matches played')),
                ('matches_won', models.IntegerField(default=0, help_text='The number of matches won by the player.', verbose_name='matches won')),
                ('matches_drawn', models.IntegerField(default=0, help_text='The number of matches drawn by the player.', verbose_name='matches drawn')),
                ('matches_lost', models.IntegerField(default=0, help_text='The number of matches lost by the player.', verbose_name='matches lost')),
                ('last_tendency', models.IntegerField(choices=[(2, '↑'), (1, '↗'), (0, '→'), (-1, '↘'), (-2, '↓')], default=0, help_text="The last tendency of the player's rating, which indicates             the direction of the player's performance in recent matches.", verbose_name='last tendency')),
                ('league', models.ForeignKey(help_text='The league the player is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league')),
                ('player', models.ForeignKey(help_text='The player who is part of the league.', on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='players.player')),
            ],
            options={
                'ordering': ['player__name', 'league__name'],
                'unique_together': {('player', 'league')},
            },
        ),
    ]
