# Generated by Django 5.2.1 on 2025-07-20 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the league.', null=True, verbose_name='description')),
                ('start_date', models.DateField(auto_now=True, help_text='The date when the league starts.', verbose_name='start date')),
                ('end_date', models.DateField(help_text='The date when the league ends.', null=True, verbose_name='end date')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaguePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1500, help_text="The player's rating in the league.", verbose_name='rating')),
                ('rd', models.FloatField(default=350, help_text="The player's rating deviation in the league.", verbose_name='rating deviation')),
                ('sigma', models.FloatField(default=0.06, help_text="The player's sigma in the league.", verbose_name='sigma')),
                ('matches_played', models.PositiveIntegerField(default=0, help_text='The number of matches played by the player in the league.', verbose_name='matches played')),
                ('matches_won', models.PositiveIntegerField(default=0, help_text='The number of matches won by the player in the league.', verbose_name='matches won')),
                ('matches_lost', models.PositiveIntegerField(default=0, help_text='The number of matches lost by the player in the league.', verbose_name='matches lost')),
                ('matches_drawn', models.PositiveIntegerField(default=0, help_text='The number of matches drawn by the player in the league.', verbose_name='matches drawn')),
                ('league', models.ForeignKey(help_text='The league the player is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.league')),
                ('player', models.ForeignKey(help_text='The player who is part of the league.', on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='players.player')),
            ],
            options={
                'ordering': ['player__name', 'league__name'],
                'unique_together': {('player', 'league')},
            },
        ),
    ]
