# Generated by Django 5.2.1 on 2025-07-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueplayer',
            options={'ordering': ['rating', 'league__name', 'player__name']},
        ),
    ]
