# Generated by Django 5.2.1 on 2025-07-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_and_formats', '0001_initial'),
        ('leagues', '0003_alter_leagueplayer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.ForeignKey(help_text='The format of the league.', on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='games_and_formats.format')),
                ('league', models.ForeignKey(help_text='The league this format belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='leagues.league')),
            ],
            options={
                'ordering': ['league__name', 'format__name'],
                'unique_together': {('league', 'format')},
            },
        ),
    ]
