# Generated by Django 5.2.4 on 2025-07-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='looser_deck',
            field=models.ForeignKey(help_text='The deck used by the looser in the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='decks.playerdeck'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_deck',
            field=models.ForeignKey(help_text='The deck used by the winner in the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='decks.playerdeck'),
        ),
        migrations.AddField(
            model_name='tournamentrating',
            name='sigma',
            field=models.FloatField(default=0.06, help_text="The volatility of the player's rating in the tournament.", verbose_name='vol'),
        ),
        migrations.AlterField(
            model_name='tournamentrating',
            name='rating',
            field=models.FloatField(default=1500, help_text='The rating of the player in the tournament.', verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='tournamentrating',
            name='rd',
            field=models.FloatField(default=350, help_text='Rating Deviation of the player in the tournament.', verbose_name='RD'),
        ),
    ]
