# Generated by Django 4.2.21 on 2025-06-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0002_rename_vol_p_player_vol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rating_deviation',
            new_name='rd',
        ),
    ]
