# Generated by Django 4.2.21 on 2025-06-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0003_rename_rating_deviation_player_rd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='elo',
            new_name='rating',
        ),
    ]
