# Generated by Django 5.2.3 on 2025-06-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0006_alter_player_options_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1500, help_text='The rating of a player, wich measures the skill level.', verbose_name='elo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rd',
            field=models.FloatField(default=350, help_text='Rating Deviation: the uncertainty in the rating of a player.', verbose_name='RD'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sigma',
            field=models.FloatField(default=0.06, help_text="The volatility of the player's rating, which measures the             consistency of the player's performance.", verbose_name='vol'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='name')),
                ('date', models.DateField(help_text='The date of the tournament.', verbose_name='date')),
                ('players', models.ManyToManyField(help_text='The players who participated in the tournament.', related_name='tournaments', to='persistence_manager.player')),
                ('winner', models.ForeignKey(help_text='The player who won the tournament.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='persistence_manager.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(help_text='The rating of the player in the tournament.', verbose_name='rating')),
                ('rd', models.FloatField(help_text='Rating Deviation of the player in the tournament.', verbose_name='RD')),
                ('player', models.ForeignKey(help_text='The player to whom this rating belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='persistence_manager.player')),
                ('tournament', models.ForeignKey(help_text='The tournament to which this rating belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='persistence_manager.tournament')),
            ],
            options={
                'ordering': ['tournament__date', '-rating', 'rd'],
            },
        ),
    ]
