# Generated by Django 5.2.3 on 2025-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0008_player_matchs_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_drawn',
            field=models.IntegerField(default=0, help_text='The number of matches drawn by the player.', verbose_name='matches drawn'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_lost',
            field=models.IntegerField(default=0, help_text='The number of matches lost by the player.', verbose_name='matches lost'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_won',
            field=models.IntegerField(default=0, help_text='The number of matches won by the player.', verbose_name='matches won'),
        ),
    ]
