# Generated by Django 5.2.3 on 2025-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0010_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_tendency',
            field=models.IntegerField(choices=[(2, '↑'), (1, '↗'), (0, '→'), (-1, '↘'), (-2, '↓')], default=0, help_text="The last tendency of the player's rating, which indicates             the direction of the player's performance in recent matches.", verbose_name='last tendency'),
        ),
    ]
