# Generated by Django 5.2.1 on 2025-07-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Indicates if the user must change their password on next login.'),
        ),
    ]
