# Generated by Django 5.2.1 on 2025-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='matches_drawn',
            field=models.IntegerField(default=0, help_text='The number of matches drawn by the player in the tournament.', verbose_name='matches drawn'),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='matches_lost',
            field=models.IntegerField(default=0, help_text='The number of matches lost by the player in the tournament.', verbose_name='matches lost'),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='matches_won',
            field=models.IntegerField(default=0, help_text='The number of matches won by the player in the tournament.', verbose_name='matches won'),
        ),
    ]
