# Generated by Django 5.2.1 on 2025-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentplayer_matches_drawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='matches_played',
            field=models.IntegerField(default=0, help_text='The number of matches won by the player in the tournament.', verbose_name='matches won'),
        ),
    ]
