# Generated by Django 5.2.1 on 2025-07-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_playerdeck_unique_together_and_more'),
        ('tournaments', '0004_tournamentplayer_last_tendency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='looser_deck',
            field=models.ForeignKey(help_text='The deck used by the looser in the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='decks.deck'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_deck',
            field=models.ForeignKey(help_text='The deck used by the winner in the match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='decks.deck'),
        ),
    ]
