# Generated by Django 5.2.1 on 2025-07-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_match_looser_deck_alter_match_winner_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='state',
            field=models.CharField(choices=[('FINISH', 'Finalizado'), ('STARTED', 'En Progreso'), ('PROGRAMMED', 'Programado')], default='PROGRAMMED', help_text='The current state of the tournament.', max_length=50),
        ),
    ]
