# Generated by Django 5.2.1 on 2025-07-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='state',
            field=models.CharField(choices=[('FINISHED', 'Finalizado'), ('STARTED', 'En Progreso'), ('PROGRAMMED', 'Programado')], default='PROGRAMMED', help_text='The current state of the tournament.', max_length=50),
        ),
    ]
