# Generated by Django 5.2.1 on 2025-07-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the game.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the game.')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the format.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the format.')),
                ('game', models.ForeignKey(help_text='The game this format belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='games_and_formats.game')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
                'ordering': ['name'],
            },
        ),
    ]
