# Generated by Django 5.2.1 on 2025-07-24 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the deck.', null=True, verbose_name='description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(help_text='The deck owned by the player.', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='decks.deck')),
                ('player', models.ForeignKey(help_text='The player who owns the deck.', on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='players.player')),
            ],
            options={
                'ordering': ['player__name', 'deck__name'],
                'unique_together': {('player', 'deck')},
            },
        ),
    ]
