# Generated by Django 5.2.1 on 2025-07-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
        ('games_and_formats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerdeck',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playerdeck',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='playerdeck',
            name='player',
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['archetype__game__id', 'archetype__id', 'name']},
        ),
        migrations.AddField(
            model_name='deck',
            name='list',
            field=models.TextField(help_text='The list of cards in the deck, formatted as a string.', null=True, verbose_name='list'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the card.', null=True, verbose_name='description')),
                ('game', models.ForeignKey(help_text='The game this card belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='games_and_formats.game')),
            ],
            options={
                'ordering': ['game__id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The number of copies of this card in the deck.', verbose_name='quantity')),
                ('card', models.ForeignKey(help_text='The card in the deck.', on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='decks.card')),
                ('deck', models.ForeignKey(help_text='The deck this card belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
            ],
            options={
                'ordering': ['card__game__id', 'deck__name', 'card__name'],
            },
        ),
        migrations.CreateModel(
            name='CardFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalityState', models.CharField(choices=[('Legal', 'Legal'), ('Banned', 'Banned'), ('Restricted', 'Restricted'), ('Illegal', 'Illegal')], default='Legal', help_text='The legality state of the card in the format.', max_length=10, verbose_name='legality state')),
                ('card', models.ForeignKey(help_text='The card in the format.', on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='decks.card')),
                ('format', models.ForeignKey(help_text='The format this card belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='games_and_formats.format')),
            ],
            options={
                'ordering': ['format__game__id', 'format__id', 'card__name'],
            },
        ),
        migrations.CreateModel(
            name='DeckArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='A brief description of the deck archetype.', null=True, verbose_name='description')),
                ('game', models.ForeignKey(help_text='The game this archetype belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='games_and_formats.game')),
            ],
            options={
                'ordering': ['game__id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='archetype',
            field=models.ForeignKey(blank=True, help_text='The archetype of the deck.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='decks.deckarchetype'),
        ),
        migrations.CreateModel(
            name='DeckArchetypeFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype', models.ForeignKey(help_text='The archetype this format belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='decks.deckarchetype')),
                ('format', models.ForeignKey(help_text='The format of the archetype.', on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='games_and_formats.format')),
            ],
            options={
                'ordering': ['format__game__id', 'format__id', 'archetype__name'],
            },
        ),
    ]
