# Generated by Django 5.2.1 on 2025-07-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_playerdeck_unique_together_and_more'),
        ('tournaments', '0005_alter_match_looser_deck_alter_match_winner_deck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerDeck',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('name', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='carddeck',
            unique_together={('deck', 'card')},
        ),
        migrations.AlterUniqueTogether(
            name='cardformat',
            unique_together={('card', 'format')},
        ),
        migrations.AlterUniqueTogether(
            name='deckarchetypeformat',
            unique_together={('archetype', 'format')},
        ),
    ]
