# Generated by Django 4.2.21 on 2025-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('elo', models.IntegerField(default=1500, verbose_name='elo')),
                ('rating_deviation', models.FloatField(default=350, verbose_name='RD')),
                ('vol_p', models.FloatField(default=0.06, verbose_name='vol')),
            ],
        ),
    ]
