# Generated by Django 5.2.3 on 2025-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0007_alter_player_rating_alter_player_rd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matchs_played',
            field=models.IntegerField(default=0, help_text='The number of matches played by the player.', verbose_name='matches played'),
        ),
    ]
