# Generated by Django 5.2.3 on 2025-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence_manager', '0009_player_matches_drawn_player_matches_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=35, verbose_name='name'),
        ),
    ]
